[package]
name = "stealth-js"
version = "0.1.0"
authors = ["Lawrence Wu <larry.wu@solana.com>"]
license = "MIT"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode = "1"
bytemuck = { version = "1.7.2", features = ["derive"] }
console_error_panic_hook = "0.1.7"
curve25519-dalek = { git = "https://github.com/lwus/curve25519-dalek", features = ["serde"] }
stealth = { path = "../../program", default-features = false, features = ["no-entrypoint"] }
getrandom = { version = "0.2", features = ["js"] }
rand_core = { version = "0.6.3" }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
sha3 = "0.9"
solana-sdk = { version = "1.9.4", default-features = false }
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }
